import type { DiscountMode, ServiceCategory, ServiceDeal } from "./service-types";

export const serviceCategories: Array<{ id: "all" | ServiceCategory; emoji: string; label: string; group: "all" | "field" | "expert" }> = [
  { id: "all", emoji: "✦", label: "전체", group: "all" },
  { id: "moving", emoji: "🚚", label: "이사·용달", group: "field" },
  { id: "moveCleaning", emoji: "🧹", label: "입주·이사청소", group: "field" },
  { id: "applianceCleaning", emoji: "❄️", label: "에어컨·가전청소", group: "field" },
  { id: "repairInstall", emoji: "🛠️", label: "출장수리·설치", group: "field" },
  { id: "interior", emoji: "🏠", label: "건축·인테리어", group: "field" },
  { id: "freight", emoji: "📦", label: "화물·운송", group: "field" },
  { id: "careerJob", emoji: "💼", label: "취업·직무", group: "field" },
  { id: "tutoringEducation", emoji: "📚", label: "과외·교육", group: "field" },
  { id: "hobbyGrowth", emoji: "🎨", label: "취미·자기계발", group: "field" },
  { id: "outsourcing", emoji: "🧑‍💻", label: "외주", group: "field" },
  { id: "eventBeauty", emoji: "🎉", label: "이벤트·뷰티", group: "field" },
  { id: "designDevelopment", emoji: "💻", label: "디자인·개발", group: "field" },
  { id: "automotive", emoji: "🚗", label: "자동차", group: "field" },
  { id: "pets", emoji: "🐾", label: "반려동물", group: "field" },
  { id: "custom", emoji: "✍️", label: "기타·직접 입력", group: "field" },
  { id: "insurance", emoji: "🛡️", label: "보험 상담", group: "expert" },
  { id: "judicialScrivener", emoji: "⚖️", label: "법무·법무사", group: "expert" },
  { id: "taxAccounting", emoji: "🧾", label: "세무·회계", group: "expert" },
  { id: "realEstateAuction", emoji: "🏢", label: "부동산·경매", group: "expert" },
  { id: "laborAdmin", emoji: "👥", label: "노무·행정", group: "expert" },
  { id: "patent", emoji: "💡", label: "특허·상표", group: "expert" },
];

export const discountModes: Array<{ id: "all" | DiscountMode; emoji: string; label: string }> = [
  { id: "all", emoji: "✦", label: "전체 방식" },
  { id: "group", emoji: "👥", label: "모이면 할인" },
  { id: "roundTrip", emoji: "↔", label: "왕복 할인" },
  { id: "neighborhood", emoji: "📍", label: "동네 묶음" },
  { id: "emptySlot", emoji: "🗓", label: "빈자리 할인" },
  { id: "priceRequest", emoji: "💬", label: "가격 제안" },
];

export const initialServiceDeals: ServiceDeal[] = [
  {
    id: 1,
    source: "provider",
    category: "moveCleaning",
    mode: "group",
    title: "성남 8월 입주청소 같이 예약",
    region: "경기 성남시 분당구",
    date: "2026-08-08 ~ 2026-08-16",
    detail: "상담 승인 고객 3명이 모이면 각자의 확정 견적에서 동일하게 10% 할인합니다.",
    discountRate: 10,
    approved: 2,
    target: 3,
    joined: 2,
    pending: 1,
    status: "recruiting",
    provider: "바른홈케어",
    verified: true,
    initialQuote: 320000,
    priceFloor: 230000,
    priceCeiling: 420000,
    priceTiers: [{ people: 3, price: 350000 }, { people: 10, price: 280000 }],
  },
  {
    id: 2,
    source: "provider",
    category: "moving",
    mode: "roundTrip",
    title: "대전↔천안 1톤 용달 왕복 매칭",
    region: "대전 유성구 · 충남 천안시",
    date: "2026-08-12",
    detail: "오전 대전→천안 작업과 오후 천안→대전 작업을 묶어 양쪽 고객에게 할인합니다.",
    discountRate: 12,
    approved: 1,
    target: 2,
    joined: 2,
    pending: 1,
    status: "recruiting",
    provider: "한길용달",
    verified: true,
    route: "대전 유성구 → 천안 서북구",
    reverseRoute: "천안 서북구 → 대전 유성구",
    vehicleTon: "1톤",
    workWindow: "오전 종료 12:30 · 상하차 각 60분",
    initialQuote: 240000,
  },
  {
    id: 3,
    source: "provider",
    category: "interior",
    mode: "neighborhood",
    title: "마포구 도배·장판 동네 묶음",
    region: "서울 마포구 성산동",
    date: "2026-08-17 ~ 2026-08-30",
    detail: "공사 동선 3km 안의 계약을 묶어 출장·자재 운반 비용을 절감합니다. 상세주소는 상담 동의 후 공개됩니다.",
    discountRate: 8,
    approved: 3,
    target: 4,
    joined: 5,
    pending: 2,
    status: "recruiting",
    provider: "공간담 인테리어",
    verified: true,
    radius: 3,
    projectPeriod: "공사 기간 8월 17일~30일",
    initialQuote: 1800000,
  },
  {
    id: 4,
    source: "provider",
    category: "applianceCleaning",
    mode: "emptySlot",
    title: "수요일 오후 에어컨 청소 빈자리",
    region: "인천 연수구",
    date: "2026-08-05 14:00~18:00",
    detail: "예약이 비는 오후 시간에 벽걸이·스탠드 에어컨 청소 상담을 받습니다.",
    discountRate: 15,
    approved: 1,
    target: 2,
    joined: 1,
    pending: 0,
    status: "recruiting",
    provider: "맑은바람케어",
    verified: true,
    emptyDate: "2026-08-05",
    initialQuote: 150000,
  },
  {
    id: 5,
    source: "customer",
    category: "repairInstall",
    mode: "priceRequest",
    title: "송파구 식기세척기 이전 설치",
    region: "서울 송파구 잠실동",
    date: "2026-08-10",
    detail: "기존 제품 철거 후 같은 동네 새 집에 재설치가 필요합니다. 배관 연장 여부는 상담 때 확인할게요.",
    discountRate: 0,
    approved: 0,
    target: 3,
    joined: 2,
    pending: 0,
    status: "recruiting",
    desiredPrice: 120000,
  },
  {
    id: 6,
    source: "customer",
    category: "freight",
    mode: "priceRequest",
    title: "화성→파주 소형 화물 운송",
    region: "경기 화성시 동탄동 → 경기 파주시",
    date: "2026-08-14",
    detail: "박스 화물 약 600kg, 지게차 상하차 가능. 같은 경로가 필요한 분을 찾습니다.",
    discountRate: 0,
    approved: 0,
    target: 2,
    joined: 1,
    pending: 0,
    status: "recruiting",
    desiredPrice: 280000,
    vehicleTon: "1톤",
  },
  {
    id: 7,
    source: "provider",
    category: "judicialScrivener",
    mode: "group",
    title: "상속등기 서류 준비 공동 의뢰",
    region: "서울·경기 · 온라인 상담",
    date: "2026-08-01 ~ 2026-08-31",
    detail: "비슷한 절차가 필요한 고객이 함께 상담을 시작하되, 사건 검토와 수임 계약은 고객별로 진행합니다.",
    discountRate: 10,
    approved: 3,
    target: 5,
    joined: 6,
    pending: 2,
    status: "recruiting",
    provider: "정담 법무사사무소",
    verified: true,
    credential: "법무사 자격 인증",
    initialQuote: 380000,
  },
  {
    id: 8,
    source: "provider",
    category: "taxAccounting",
    mode: "group",
    title: "개인사업자 세무 신고 공동계약",
    region: "전국 · 비대면 가능",
    date: "2026-08-01 ~ 2026-08-20",
    detail: "개인사업자 10명이 모이면 각자의 자료와 난이도에 따라 확정한 견적에 동일 할인율을 적용합니다.",
    discountRate: 12,
    approved: 7,
    target: 10,
    joined: 7,
    pending: 3,
    status: "recruiting",
    provider: "이음 세무회계",
    verified: true,
    credential: "세무사 자격 인증",
    initialQuote: 220000,
    priceFloor: 180000,
    priceCeiling: 320000,
    priceTiers: [{ people: 3, price: 280000 }, { people: 10, price: 200000 }],
  },
  {
    id: 9,
    source: "provider",
    category: "realEstateAuction",
    mode: "group",
    title: "수도권 부동산 경매 권리분석 공동 자문",
    region: "서울·경기·인천",
    date: "2026-08-10 19:00",
    detail: "관심 물건은 고객별로 검토하고, 공통 교육과 권리분석 상담 일정을 묶어 공동계약을 진행합니다.",
    discountRate: 15,
    approved: 4,
    target: 8,
    joined: 11,
    pending: 2,
    status: "recruiting",
    provider: "바른경매 컨설팅",
    verified: true,
    credential: "전문가·사업자 인증",
    initialQuote: 300000,
  },
  {
    id: 10,
    source: "customer",
    category: "insurance",
    mode: "priceRequest",
    title: "자영업자 기존 보험 보장분석 공동 상담",
    region: "전국 · 온라인 상담",
    date: "2026-08-18",
    detail: "보험 가입 권유보다 기존 계약의 보장 내역과 중복 여부를 함께 점검할 인증 전문가를 찾습니다.",
    discountRate: 0,
    approved: 0,
    target: 5,
    joined: 4,
    pending: 1,
    status: "recruiting",
    desiredPrice: 50000,
    priceFloor: 40000,
    priceCeiling: 80000,
  },
  {
    id: 11,
    source: "provider",
    category: "laborAdmin",
    mode: "group",
    title: "소규모 사업장 노무관리 공동계약",
    region: "서울·경기 · 비대면 가능",
    date: "2026-08-01 ~ 2026-09-30",
    detail: "취업규칙과 근로계약서 점검이 필요한 소규모 사업장을 모아 고객별 자문 계약을 진행합니다.",
    discountRate: 10,
    approved: 2,
    target: 5,
    joined: 7,
    pending: 2,
    status: "recruiting",
    provider: "다온 노무사사무소",
    verified: true,
    credential: "공인노무사 자격 인증",
    initialQuote: 250000,
  },
  {
    id: 12,
    source: "provider",
    category: "patent",
    mode: "group",
    title: "소상공인 상표 출원 공동 의뢰",
    region: "전국 · 비대면 가능",
    date: "2026-08-05 ~ 2026-08-28",
    detail: "출원 가능성 검토와 지정상품 상담은 개별 진행하고, 같은 기간 접수 업무를 묶어 공동계약합니다.",
    discountRate: 8,
    approved: 4,
    target: 6,
    joined: 9,
    pending: 1,
    status: "recruiting",
    provider: "새봄 특허사무소",
    verified: true,
    credential: "변리사 자격 인증",
    initialQuote: 420000,
  },
];
