import type { DiscountMode, ServiceCategory, ServiceDeal } from "./service-types";

export const serviceCategories: Array<{ id: "all" | ServiceCategory; emoji: string; label: string }> = [
  { id: "all", emoji: "✦", label: "전체" },
  { id: "moving", emoji: "🚚", label: "이사·용달" },
  { id: "moveCleaning", emoji: "🧹", label: "입주·이사청소" },
  { id: "applianceCleaning", emoji: "❄️", label: "에어컨·가전청소" },
  { id: "repairInstall", emoji: "🛠️", label: "출장수리·설치" },
  { id: "interior", emoji: "🏠", label: "건축·인테리어" },
  { id: "freight", emoji: "📦", label: "화물·운송" },
];

export const discountModes: Array<{ id: "all" | DiscountMode; emoji: string; label: string }> = [
  { id: "all", emoji: "✦", label: "전체 방식" },
  { id: "group", emoji: "👥", label: "모이면 할인" },
  { id: "roundTrip", emoji: "↔", label: "왕복 할인" },
  { id: "neighborhood", emoji: "📍", label: "동네 묶음" },
  { id: "emptySlot", emoji: "🗓", label: "빈자리 할인" },
  { id: "priceRequest", emoji: "💬", label: "가격 제안" },
];

export const initialServiceDeals: ServiceDeal[] = [
  {
    id: 1,
    source: "provider",
    category: "moveCleaning",
    mode: "group",
    title: "성남 8월 입주청소 같이 예약",
    region: "경기 성남시 분당구",
    date: "2026-08-08 ~ 2026-08-16",
    detail: "상담 승인 고객 3명이 모이면 각자의 확정 견적에서 동일하게 10% 할인합니다.",
    discountRate: 10,
    approved: 2,
    target: 3,
    joined: 2,
    pending: 1,
    status: "recruiting",
    provider: "바른홈케어",
    verified: true,
    initialQuote: 320000,
  },
  {
    id: 2,
    source: "provider",
    category: "moving",
    mode: "roundTrip",
    title: "대전↔천안 1톤 용달 왕복 매칭",
    region: "대전 유성구 · 충남 천안시",
    date: "2026-08-12",
    detail: "오전 대전→천안 작업과 오후 천안→대전 작업을 묶어 양쪽 고객에게 할인합니다.",
    discountRate: 12,
    approved: 1,
    target: 2,
    joined: 2,
    pending: 1,
    status: "recruiting",
    provider: "한길용달",
    verified: true,
    route: "대전 유성구 → 천안 서북구",
    reverseRoute: "천안 서북구 → 대전 유성구",
    vehicleTon: "1톤",
    workWindow: "오전 종료 12:30 · 상하차 각 60분",
    initialQuote: 240000,
  },
  {
    id: 3,
    source: "provider",
    category: "interior",
    mode: "neighborhood",
    title: "마포구 도배·장판 동네 묶음",
    region: "서울 마포구 성산동",
    date: "2026-08-17 ~ 2026-08-30",
    detail: "공사 동선 3km 안의 계약을 묶어 출장·자재 운반 비용을 절감합니다. 상세주소는 상담 동의 후 공개됩니다.",
    discountRate: 8,
    approved: 3,
    target: 4,
    joined: 5,
    pending: 2,
    status: "recruiting",
    provider: "공간담 인테리어",
    verified: true,
    radius: 3,
    projectPeriod: "공사 기간 8월 17일~30일",
    initialQuote: 1800000,
  },
  {
    id: 4,
    source: "provider",
    category: "applianceCleaning",
    mode: "emptySlot",
    title: "수요일 오후 에어컨 청소 빈자리",
    region: "인천 연수구",
    date: "2026-08-05 14:00~18:00",
    detail: "예약이 비는 오후 시간에 벽걸이·스탠드 에어컨 청소 상담을 받습니다.",
    discountRate: 15,
    approved: 1,
    target: 2,
    joined: 1,
    pending: 0,
    status: "recruiting",
    provider: "맑은바람케어",
    verified: true,
    emptyDate: "2026-08-05",
    initialQuote: 150000,
  },
  {
    id: 5,
    source: "customer",
    category: "repairInstall",
    mode: "priceRequest",
    title: "송파구 식기세척기 이전 설치",
    region: "서울 송파구 잠실동",
    date: "2026-08-10",
    detail: "기존 제품 철거 후 같은 동네 새 집에 재설치가 필요합니다. 배관 연장 여부는 상담 때 확인할게요.",
    discountRate: 0,
    approved: 0,
    target: 3,
    joined: 2,
    pending: 0,
    status: "recruiting",
    desiredPrice: 120000,
  },
  {
    id: 6,
    source: "customer",
    category: "freight",
    mode: "priceRequest",
    title: "화성→파주 소형 화물 운송",
    region: "경기 화성시 동탄동 → 경기 파주시",
    date: "2026-08-14",
    detail: "박스 화물 약 600kg, 지게차 상하차 가능. 같은 경로가 필요한 분을 찾습니다.",
    discountRate: 0,
    approved: 0,
    target: 2,
    joined: 1,
    pending: 0,
    status: "recruiting",
    desiredPrice: 280000,
    vehicleTon: "1톤",
  },
];
